import {readFileSync,writeFileSync,mkdirSync,copyFileSync} from 'node:fs';
import {Script} from 'node:vm';
import assert from 'node:assert/strict';
const root=new URL('./',import.meta.url);
const html=readFileSync(new URL('index.html',root),'utf8');
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
assert.equal(ids.length,new Set(ids).size,'IDs duplicados na página');
for(const file of ['app.js','dashboard.js']){
 const source=readFileSync(new URL(file,root),'utf8');new Script(source,{filename:file});
 for(const [,id] of source.matchAll(/\bel\('([^']+)'\)/g))assert(ids.includes(id),'Elemento ausente: '+id);
}
assert(html.includes("script-src 'self'"),'Scripts locais bloqueados');
assert(html.includes('id="allocationTarget"'),'Seletor de destino da planilha ausente');
assert(html.includes('value="single"'),'Opção de envio para um único consultor ausente');
assert(html.includes('id="dayFilter"'),'Filtro de dia ausente');
assert(html.includes('id="clearDayFilter"'),'Ação para limpar o filtro de dia ausente');
assert(html.includes('id="redistributeUnworked"'),'Opção segura de redistribuição ausente');
assert(html.includes('value="smart" selected'),'Distribuição inteligente não é o padrão');
assert(html.includes('id="uploadProgress"'),'Carregamento da planilha ausente');
assert(html.includes('id="uploadDraftStatus"'),'Status do rascunho ausente');
assert(html.includes('id="uploadDropZone"'),'Área rápida para selecionar a planilha ausente');
assert(html.includes('id="fileQuickStatus"'),'Resumo rápido do arquivo ausente');
assert(html.includes('class="advanced-settings"'),'Configurações avançadas não foram simplificadas');
assert(html.includes('id="uploadReadySummary"'),'Resumo de confirmação ausente');
const dashboard=readFileSync(new URL('dashboard.js',root),'utf8');
assert(dashboard.includes("el('allocationTarget').value==='single'"),'Regra de seleção única ausente');
assert(dashboard.includes("distribution_mode:single?'equal'"),'Envio único deve usar a distribuição integral existente');
assert(dashboard.includes("redistribute_unworked:String(el('redistributeUnworked').checked)"),'Redistribuição segura não enviada ao servidor');
assert(dashboard.includes('if(file)analyzeSelectedFile()'),'Planilha não inicia análise automática');
assert(dashboard.includes("const uploadDraftKey='df_upload_draft_v3'"),'Rascunho do modal não persistido');
assert(dashboard.includes("mode!=='smart'"),'Cálculo inteligente por carga ausente');
assert(dashboard.includes('analysisCache.set'),'Reutilização rápida da análise ausente');
assert(dashboard.includes('campaignFromFile(file)'),'Nome automático da campanha ausente');
assert(dashboard.includes("people.forEach(p=>allocationDraft.set(p.id,{selected:true,count:0}))"),'Seleção automática da equipe ausente');
const app=readFileSync(new URL('app.js',root),'utf8');
assert(app.includes('day:selectedDay'),'Filtro de dia não enviado ao servidor');
assert(app.includes("selectedDay=result.selected_day||''"),'Dia confirmado pelo servidor não aplicado');
mkdirSync(new URL('dist/',root),{recursive:true});
for(const file of ['index.html','app.js','dashboard.js','styles.css','logo.png','privacidade.html','suporte.html','exclusao-de-dados.html'])copyFileSync(new URL(file,root),new URL('dist/'+file,root));
console.log('Painel validado e arquivos públicos preparados.');
