const paths={grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M16 3a4 4 0 0 1 0 8 M22 21v-2a4 4 0 0 0-3-3.87 M9 3a4 4 0 1 0 0 8a4 4 0 0 0 0-8',folder:'M3 7V4h6l2 3h10v13H3Z',contact:'M5 3h15v18H5z M3 7h3 M3 12h3 M3 17h3 M9 17v-1a3 3 0 0 1 6 0v1 M12 7a2 2 0 1 0 0 4a2 2 0 0 0 0-4',activity:'M2 12h5l3-8 4 16 3-8h5',shield:'M12 3 3 7v5c0 5 9 9 9 9s9-4 9-9V7z M8 12l3 3 5-6',menu:'M3 6h18 M3 12h18 M3 18h18',upload:'M12 16V3 M7 8l5-5 5 5 M3 15v6h18v-6',filter:'M3 4h18l-7 8v8l-4-2v-6z',refresh:'M20 8a8 8 0 0 0-14-3L3 8 M3 3v5h5 M4 16a8 8 0 0 0 14 3l3-3 M21 21v-5h-5',phone:'M4 3h4l2 5-3 2a15 15 0 0 0 7 7l2-3 5 2v4c-9 3-21-9-17-17z',chart:'M3 3v18h18 M7 15l5-6 4 3 5-7',search:'M10 3a7 7 0 1 0 0 14a7 7 0 0 0 0-14 M15 15l6 6'};
document.querySelectorAll('[data-icon]').forEach(n=>n.innerHTML='<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="'+paths[n.dataset.icon]+'"/></svg>');
const viewLabels={dashboard:['Visão geral','Acompanhe os resultados e o ritmo da sua equipe.'],team:['Consultores','Gerencie acessos e acompanhe a operação de cada pessoa.'],campaigns:['Planilhas e campanhas','Distribua novos contatos e gerencie suas campanhas.'],clients:['Clientes / CRM','Consulte o histórico e os próximos passos de cada cliente.'],activity:['Atividades','Acompanhe o que acontece na sua operação.']};
function closeMenu(){el('sidebar').classList.remove('open');el('navBackdrop').classList.add('hidden');el('menuToggle').setAttribute('aria-expanded','false')}
function showView(view){if(!viewLabels[view])view='dashboard';document.querySelectorAll('[data-section]').forEach(n=>n.classList.toggle('hidden',n.dataset.section!==view));document.querySelectorAll('[data-view]').forEach(n=>{n.classList.toggle('active',n.dataset.view===view);if(n.dataset.view===view)n.setAttribute('aria-current','page');else n.removeAttribute('aria-current')});el('pageTitle').textContent=viewLabels[view][0];el('breadcrumbTitle').textContent=viewLabels[view][0];el('pageDescription').textContent=viewLabels[view][1];history.replaceState(null,'','#'+view);closeMenu()}
document.querySelectorAll('[data-view],[data-go]').forEach(n=>n.onclick=()=>showView(n.dataset.view||n.dataset.go));
el('menuToggle').onclick=()=>{el('sidebar').classList.toggle('open');const open=el('sidebar').classList.contains('open');el('navBackdrop').classList.toggle('hidden',!open);el('menuToggle').setAttribute('aria-expanded',String(open))};el('navBackdrop').onclick=closeMenu;
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
document.querySelectorAll('[data-open]').forEach(n=>n.onclick=()=>{if(n.dataset.open==='uploadDialog'&&selectedConsultant)el('assignedTo').value=selectedConsultant;el(n.dataset.open).showModal();document.body.classList.add('modal-open')});
document.querySelectorAll('[data-close]').forEach(n=>n.onclick=()=>n.closest('dialog').close());
document.querySelectorAll('dialog').forEach(n=>n.addEventListener('close',()=>document.body.classList.remove('modal-open')));
window.addEventListener('hashchange',()=>showView(location.hash.slice(1)));showView(location.hash.slice(1));
function normalizeSearch(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
const numberFormat=new Intl.NumberFormat('pt-BR');
const number=value=>numberFormat.format(metricNumber(value));
el('consultantFilter').onchange=()=>{selectedConsultant=el('consultantFilter').value;selectedCampaign='';leadOffset=0;refresh()};
for(const id of ['teamSearch','teamStatus','campaignSearch','campaignStatus'])el(id).addEventListener(id.endsWith('Search')?'input':'change',()=>{if(overview){render();renderDashboard()}});
function renderDashboard(){
  const {consultants=[],campaigns=[],charts,metrics={}}=overview;
  const scoped=consultants.filter(p=>!selectedConsultant||p.id===selectedConsultant);
  const scopedCampaigns=campaigns.filter(c=>!selectedConsultant||c.assigned_to===selectedConsultant);
  el('sLeads').textContent=number(metrics.total);el('sCalls').textContent=number(metrics.dialed);
  el('activeCaption').textContent=selectedConsultant?'No filtro selecionado':consultants.length+' consultores cadastrados';
  el('pendingCaption').textContent=number(metrics.pending)+' clientes pendentes';
  el('connectedCaption').textContent=number(metrics.connected)+' com contato registrado';
  if(!charts){el('dailyChart').innerHTML=el('outcomeChart').innerHTML='<div class="empty">Os gráficos estarão disponíveis após a atualização do servidor.</div>';return}
  const daily=charts.daily||[],total=daily.reduce((s,d)=>s+metricNumber(d.total),0),max=Math.max(1,...daily.map(d=>metricNumber(d.total)));
  el('trendTotal').textContent=number(total)+' tentativas';
  const width=700,height=236,left=40,top=22,plot=170,step=90,barWidth=38;
  let graph='';for(let i=0;i<=4;i++){const y=top+plot-i*plot/4;graph+='<line class="grid-line" x1="'+left+'" x2="690" y1="'+y+'" y2="'+y+'"/><text x="30" y="'+(y+4)+'" text-anchor="end">'+number(Math.ceil(max*i/4))+'</text>'}
  daily.forEach((d,i)=>{const count=metricNumber(d.total),h=count/max*plot,x=left+20+i*step,date=d.day.slice(8,10)+'/'+d.day.slice(5,7);graph+='<rect class="bar" x="'+x+'" y="'+(top+plot-h)+'" width="'+barWidth+'" height="'+h+'" rx="5"><title>'+esc(date)+': '+number(count)+' tentativas</title></rect><text x="'+(x+barWidth/2)+'" y="'+(top+plot-h-7)+'" text-anchor="middle">'+number(count)+'</text><text x="'+(x+barWidth/2)+'" y="218" text-anchor="middle">'+esc(date)+'</text>'});
  const graphDescription=daily.map(d=>d.day+': '+number(d.total)+' tentativas').join('; ');
  el('dailyChart').innerHTML='<svg class="chart-svg" viewBox="0 0 '+width+' '+height+'" role="img" aria-label="'+esc(graphDescription)+'">'+graph+'</svg><div class="chart-key"><i></i>'+(total?'Tentativas de ligação iniciadas no aplicativo':'Nenhuma tentativa iniciada neste período')+'</div>';
  const colors={pending:'#dce8de',completed:'#3b9d71',unreached:'#e9ba64',active:'#8db4e3',blocked:'#c88488'};
  const outcomes=charts.outcomes||[],all=outcomes.reduce((s,x)=>s+metricNumber(x.value),0);let offset=0;
  const arcs=outcomes.map(x=>{const portion=all?metricNumber(x.value)*100/all:0;const arc='<circle cx="50" cy="50" r="40" pathLength="100" fill="none" stroke="'+colors[x.key]+'" stroke-width="12" stroke-dasharray="'+portion+' '+(100-portion)+'" stroke-dashoffset="'+(-offset)+'"/>';offset+=portion;return portion?arc:''}).join('');
  el('outcomeChart').innerHTML='<div class="donut"><svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="40" fill="none" stroke="#eff3ef" stroke-width="12"/>'+arcs+'</svg><div class="donut-label"><strong>'+number(all)+'</strong><span>clientes</span></div></div><div class="legend">'+outcomes.map(x=>'<div class="legend-row"><i style="background:'+colors[x.key]+'"></i><span>'+esc(x.label)+'</span><strong>'+number(x.value)+'</strong></div>').join('')+'</div>';
  const ranked=[...scoped].sort((a,b)=>b.connected_count-a.connected_count).slice(0,5),best=Math.max(1,...ranked.map(p=>metricNumber(p.connected_count)));
  el('ranking').innerHTML=ranked.length?ranked.map((p,i)=>'<button class="rank-row" data-consultant="'+esc(p.id)+'"><span class="rank-number">'+String(i+1).padStart(2,'0')+'</span><span class="rank-name">'+esc(p.display_name)+'<small>'+number(p.dialed_count)+' clientes discados</small></span><span class="progress"><i style="width:'+Math.min(100,metricNumber(p.connected_count)/best*100)+'%"></i></span><span class="rank-value">'+number(p.connected_count)+'<small>'+number(p.contact_rate)+'%</small></span></button>').join(''):'<div class="empty">Crie um consultor para começar a acompanhar a equipe.</div>';
  el('campaignOverview').innerHTML=scopedCampaigns.length?scopedCampaigns.slice(0,5).map(c=>'<button class="campaign-summary" data-campaign="'+esc(c.id)+'"><div><strong>'+esc(c.name)+'</strong><span class="badge '+(c.status==='running'?'green':'')+'">'+esc(statusName[c.status]||c.status)+'</span></div><div><small>'+esc(c.consultant_name)+'</small><small>'+number(c.completed)+' / '+number(c.total)+'</small></div><div class="progress"><i style="width:'+Math.min(100,c.total?c.completed/c.total*100:0)+'%"></i></div></button>').join(''):'<div class="empty">Nenhuma campanha neste filtro. Envie uma nova planilha para distribuir contatos.</div>';
  renderManagement(scoped,scopedCampaigns);
}
function renderManagement(people,campaigns){
  const tq=normalizeSearch(el('teamSearch').value),ts=el('teamStatus').value;
  const shown=people.filter(p=>(!tq||normalizeSearch(p.display_name+' '+p.username).includes(tq))&&(!ts||(ts==='active'?p.active:!p.active)));
  el('teamBody').innerHTML=shown.length?shown.map(p=>'<tr><td><strong>'+esc(p.display_name)+'</strong></td><td>'+esc(p.username)+'</td><td>'+number(p.campaign_count)+' campanhas<br><small>'+number(p.lead_count)+' clientes · '+number(p.connected_count)+' contatos</small></td><td><span class="badge '+(p.active?'green':'amber')+'">'+(p.active?'Ativo':'Bloqueado')+'</span></td><td>'+fmtDate(p.last_seen_at)+'</td><td><div class="actions"><button class="mini" data-consultant="'+esc(p.id)+'">Ver operação</button><button class="mini" data-action="'+(p.active?'block':'activate')+'" data-id="'+esc(p.id)+'">'+(p.active?'Bloquear':'Ativar')+'</button><button class="mini" data-action="password" data-id="'+esc(p.id)+'">Nova senha</button><button class="mini danger" data-action="delete_consultant" data-id="'+esc(p.id)+'">Excluir</button></div></td></tr>').join(''):'<tr><td colspan="6" class="empty">Nenhum consultor neste filtro.</td></tr>';
  const cq=normalizeSearch(el('campaignSearch').value),cs=el('campaignStatus').value;
  const filtered=campaigns.filter(c=>(!cq||normalizeSearch(c.name+' '+c.source_filename).includes(cq))&&(!cs||c.status===cs));
  el('campaignBody').innerHTML=filtered.length?filtered.map(c=>'<tr><td><strong>'+esc(c.name)+'</strong><br><small>'+esc(c.source_filename)+'</small></td><td>'+esc(c.consultant_name)+'</td><td>'+number(c.completed)+' / '+number(c.total)+'<div class="progress"><i style="width:'+Math.min(100,c.total?c.completed/c.total*100:0)+'%"></i></div></td><td><span class="badge '+(c.status==='running'?'green':'')+'">'+esc(statusName[c.status]||c.status)+'</span><br><small>'+number(c.allowed_start_hour)+'h–'+number(c.allowed_end_hour)+'h · '+number(c.max_attempts_per_lead)+' tentativas · '+number(c.max_daily_calls)+'/dia</small></td><td><div class="actions"><button class="mini" data-campaign="'+esc(c.id)+'">Ver contatos</button><button class="mini danger" data-action="delete_campaign" data-id="'+esc(c.id)+'">Excluir planilha</button></div></td></tr>').join(''):'<tr><td colspan="5" class="empty">Nenhuma campanha neste filtro.</td></tr>';
}
async function loadConsultant(id){selectedConsultant=id;selectedCampaign='';leadOffset=0;showView('dashboard');await refresh()}
async function loadLeads(id){selectedCampaign=id;leadOffset=0;showView('clients');await refresh()}
function resetPassword(id){openAction('password',id)}
function toggleConsultant(id,active){openAction(active?'activate':'block',id)}
let pendingAction=null;
function openAction(action,id){
 const item=action==='delete_campaign'?overview.campaigns.find(x=>x.id===id):overview.consultants.find(x=>x.id===id);if(!item)return;
 const name=item.display_name||item.name, descriptions={delete_consultant:['Excluir consultor','O acesso de “'+name+'” será bloqueado e suas campanhas serão retiradas da operação. Histórico e reservas de telefones serão preservados. Finalize qualquer ligação ou tabulação antes de excluir.','Excluir consultor'],delete_campaign:['Excluir planilha','A campanha “'+name+'” será retirada da operação e deixará de aparecer no Android após sincronizar. Histórico e reservas de telefones serão preservados para evitar contatos repetidos.','Excluir planilha'],password:['Redefinir senha','Informe a nova senha de “'+name+'” (mínimo de 8 caracteres).','Salvar senha'],block:['Bloquear acesso','“'+name+'” deixará de acessar o sistema. As campanhas e o histórico serão mantidos.','Bloquear'],activate:['Ativar acesso','Liberar novamente o acesso de “'+name+'” ao aplicativo?','Ativar']};
 const info=descriptions[action];if(!info)return;pendingAction={action,id};el('actionDialogTitle').textContent=info[0];el('actionDescription').textContent=info[1];el('actionSubmit').textContent=info[2];el('actionSubmit').className=action.startsWith('delete')||action==='block'?'danger':'primary';el('actionPasswordField').classList.toggle('hidden',action!=='password');el('actionPassword').required=action==='password';el('actionPassword').value='';el('actionMsg').textContent='';el('actionDialog').showModal();document.body.classList.add('modal-open');
}
document.addEventListener('click',e=>{const n=e.target.closest('[data-consultant],[data-campaign],[data-action]');if(!n)return;if(n.dataset.consultant)loadConsultant(n.dataset.consultant);else if(n.dataset.campaign)loadLeads(n.dataset.campaign);else openAction(n.dataset.action,n.dataset.id)});
el('actionForm').onsubmit=async e=>{e.preventDefault();if(!pendingAction||mutationPending)return;const form=e.currentTarget,{action,id}=pendingAction;mutationPending=true;busy(form,true);el('actionMsg').textContent='Salvando alteração…';let done=false;try{if(action==='password')await api('reset_password',{id,password:el('actionPassword').value});else if(action==='activate'||action==='block')await api('set_consultant_active',{id,active:action==='activate'});else await api(action,{id});done=true;if(action==='delete_consultant'&&(selectedConsultant===id||overview.campaigns.some(c=>c.id===selectedCampaign&&c.assigned_to===id))){selectedConsultant='';selectedCampaign='';leadOffset=0}if(action==='delete_campaign'&&selectedCampaign===id){selectedCampaign='';leadOffset=0}await refresh(false,true);el('actionDialog').close();toast(action.startsWith('delete')?'Removido da operação. Histórico e proteção dos contatos preservados.':'Alteração salva com sucesso.')}catch(err){el('actionMsg').textContent=(done?'Alteração salva. Atualize a lista. ':'')+err.message}finally{mutationPending=false;busy(form,false)}};
Object.assign(eventName,{CONSULTANT_REMOVED:'Consultor excluído',CAMPAIGN_REMOVED:'Planilha excluída'});
